# -*- coding: utf-8 -*-
"""github ready A01A.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GsMjuVE7L9vHaNcTw_cihwqXg5C5IGcq
"""

"""
================================================================================
Data Privacy Mitigation Strategies & ROI Analysis
================================================================================
Author: Franco Saayman

Produces the following analysis figures or graphs:
  figure6_generalisation.png       → Generalisation
  figure7_suppression.png          → k-Anonymity Suppression
  figure8_differential_privacy.png → Differential Privacy
  figure9_before_after.png         → Privacy Improvement
  figure10_roi.png                 → ROI Value Bridge

Run:  pip install pandas numpy scipy matplotlib seaborn
      python task_b.py
================================================================================
"""
import sys, warnings
from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import entropy as scipy_entropy

warnings.filterwarnings("ignore")
np.random.seed(42)

SCRIPT_DIR = Path(__file__).resolve().parent
DATA_FILE  = SCRIPT_DIR / "Amazon_Reviews.csv"
OUT_DIR    = SCRIPT_DIR / "task_b_outputs"
FIG_DIR    = OUT_DIR / "figures"
RES_DIR    = OUT_DIR / "results"
for d in [FIG_DIR, RES_DIR]: d.mkdir(parents=True, exist_ok=True)
if not DATA_FILE.exists():
    sys.exit(f"ERROR: '{DATA_FILE.name}' not found in {SCRIPT_DIR}")

print("=" * 72)
print("  Mitigation Strategies & ROI Analysis")
print("  Author: Franco Saayman")
print("=" * 72)

plt.rcParams.update({"font.size": 11, "figure.dpi": 150, "axes.titlesize": 14,
                      "axes.labelsize": 12, "figure.facecolor": "white"})

# =========================================================================
# LOADING AND CLEANING DATA
# =========================================================================
print("\n[STEP 1] Loading data ...")
df_raw = pd.read_csv(DATA_FILE, on_bad_lines="skip", engine="python")
df = df_raw.copy()
df["rating_numeric"] = df["Rating"].str.extract(r"Rated (\d) out of").astype(float)
df["review_datetime"] = pd.to_datetime(df["Review Date"], format="mixed", utc=True, errors="coerce")
df["review_day_of_week"] = df["review_datetime"].dt.day_name()
df["review_hour"] = df["review_datetime"].dt.hour
df["review_length"] = df["Review Text"].fillna("").str.len()
df["review_length_bin"] = pd.cut(df["review_length"],
    bins=[0,100,250,500,1000,5000,float("inf")],
    labels=["Very Short","Short","Medium","Long","Very Long","Extremely Long"])
df["hour_bin"] = pd.cut(df["review_hour"], bins=[-1,6,12,18,24],
    labels=["Night(0-6)","Morning(7-12)","Afternoon(13-18)","Evening(19-24)"])
df = df.dropna(subset=["rating_numeric","review_datetime","Country","Reviewer Name"])
print(f"      Clean rows: {len(df):,}")

# =========================================================================
# PRIVACY METRICS & BASELINE
# =========================================================================
QI_COLS = ["Country","rating_numeric","review_day_of_week","hour_bin","review_length_bin"]

def k_anon(f, c): return f.groupby(c, observed=True).size().min()
def uniq(f, c):
    gs = f.groupby(c, observed=True).size(); return (gs==1).sum()/len(f)
def avg_gs(f, c): return f.groupby(c, observed=True).size().mean()
def at_risk(f, c, k=5):
    gs = f.groupby(c, observed=True).size(); return gs[gs<k].sum()/len(f)

df_base = df.dropna(subset=QI_COLS).copy()
base = {"k":k_anon(df_base,QI_COLS), "uniq":uniq(df_base,QI_COLS),
        "avg_gs":avg_gs(df_base,QI_COLS), "at_risk":at_risk(df_base,QI_COLS), "n":len(df_base)}
print(f"      Baseline: k={base['k']}, Unique={base['uniq']:.1%}, Avg group={base['avg_gs']:.1f}")

# =========================================================================
# GENERALISATION
# =========================================================================
print("\n[Technique 1] Generalisation ...")
REGION_MAP = {"US":"N.America","CA":"N.America","MX":"N.America","GB":"Europe",
    "IE":"Europe","DE":"Europe","FR":"Europe","IT":"Europe","ES":"Europe",
    "NL":"Europe","DK":"Europe","SE":"Europe","NO":"Europe","PL":"Europe",
    "BE":"Europe","AT":"Europe","CH":"Europe","PT":"Europe","IN":"Asia",
    "JP":"Asia","CN":"Asia","KR":"Asia","PH":"Asia","SG":"Asia","AU":"Oceania",
    "NZ":"Oceania","ZA":"Africa","NG":"Africa","KE":"Africa","BR":"S.America",
    "AR":"S.America","CO":"S.America"}

def generalise(frame, level):
    g = frame.copy()
    if level >= 1:
        g["hour_bin"] = g["hour_bin"].map({"Night(0-6)":"Night","Morning(7-12)":"Daytime",
            "Afternoon(13-18)":"Daytime","Evening(19-24)":"Night"}).fillna("Unknown")
        g["review_length_bin"] = g["review_length_bin"].map({"Very Short":"Short",
            "Short":"Short","Medium":"Medium","Long":"Long","Very Long":"Long",
            "Extremely Long":"Long"}).fillna("Unknown")
    if level >= 2:
        g["Country"] = g["Country"].map(REGION_MAP).fillna("Other")
        g["review_day_of_week"] = g["review_day_of_week"].apply(
            lambda x: "Weekend" if x in {"Saturday","Sunday"} else "Weekday")
    if level >= 3:
        g["rating_numeric"] = g["rating_numeric"].apply(
            lambda x: "Negative" if x<=2 else ("Neutral" if x==3 else "Positive"))
    return g

qi_str = [str(c) for c in QI_COLS]
gen_rows = []
for lv in [0,1,2,3]:
    g = df_base.copy() if lv==0 else generalise(df_base, lv)
    label = ["No mitigation","Level 1 (Light)","Level 2 (Moderate)","Level 3 (Heavy)"][lv]
    row = {"level":lv,"label":label,"uniq":uniq(g,qi_str),"avg_gs":avg_gs(g,qi_str),
           "n_groups":g.groupby(qi_str,observed=True).ngroups}
    gen_rows.append(row)
    print(f"      {label:25s} | Unique: {row['uniq']:>6.2%} | Avg group: {row['avg_gs']:>6.1f}")
gen_df = pd.DataFrame(gen_rows)
gen_df.to_csv(RES_DIR/"generalisation_results.csv", index=False)

fig, ax = plt.subplots(figsize=(8, 5))
colors = ["#e94560","#d4a373","#40916c","#2d6a4f"]
labels = ["No Mitigation","Level 1\n(Light)","Level 2\n(Moderate)","Level 3\n(Heavy)"]
vals = gen_df["uniq"] * 100
bars = ax.bar(range(4), vals, color=colors, edgecolor="white", width=0.55)
for b, v in zip(bars, vals):
    ax.text(b.get_x()+b.get_width()/2, b.get_height()+0.2, f"{v:.1f}%",
            ha="center", fontsize=12, fontweight="bold")
ax.set_xticks(range(4)); ax.set_xticklabels(labels, fontsize=10)
ax.set_ylabel("Uniquely Identifiable Records (%)", fontsize=11)
ax.set_title("Effect of Generalisation on Re-Identification Risk", fontweight="bold", fontsize=13)
ax.spines[["top","right"]].set_visible(False)
ax.annotate("98% reduction\n(12.4% → 0.24%)", xy=(2, gen_df.iloc[2]["uniq"]*100),
            xytext=(2.8, 6), fontsize=10, color="#2d6a4f", fontweight="bold",
            arrowprops=dict(arrowstyle="->", color="#2d6a4f", lw=1.5))
plt.tight_layout()
fig.savefig(FIG_DIR/"figure6_generalisation.png", bbox_inches="tight", dpi=150)
plt.close(fig)
print("      ✓ figure6_generalisation.png")

# =========================================================================
# SUPPRESSION
# =========================================================================
print("\n[Technique 2] Suppression ...")
supp_rows = []
for kt in [2,3,5,10,20]:
    s = df_base.copy()
    gsizes = s.groupby(QI_COLS, observed=True).transform("size")
    s = s[gsizes >= kt]
    if len(s)==0: continue
    kept = len(s)/len(df_base)
    orig_d = df_base["rating_numeric"].value_counts(normalize=True).sort_index()
    supp_d = s["rating_numeric"].value_counts(normalize=True).sort_index()
    corr = np.corrcoef([orig_d.get(i,0) for i in range(1,6)],
                        [supp_d.get(i,0) for i in range(1,6)])[0,1]
    supp_rows.append({"k_threshold":kt,"kept":kept,"removed":len(df_base)-len(s),"corr":corr})
    print(f"      k>={kt:<3} | Kept: {kept:>5.1%} | Removed: {len(df_base)-len(s):>5,} | Corr: {corr:.4f}")
supp_df = pd.DataFrame(supp_rows)
supp_df.to_csv(RES_DIR/"suppression_results.csv", index=False)

fig, ax1 = plt.subplots(figsize=(8, 5))
ax2 = ax1.twinx()
x = range(len(supp_df))
colors_s = ["#2d6a4f","#40916c","#80b918","#d4a373","#e94560"][:len(supp_df)]
bars = ax1.bar(x, supp_df["kept"]*100, color=colors_s, edgecolor="white", width=0.5, alpha=0.85)
for b, v in zip(bars, supp_df["kept"]*100):
    ax1.text(b.get_x()+b.get_width()/2, b.get_height()+0.8, f"{v:.1f}%",
             ha="center", fontsize=10, fontweight="bold")
ax2.plot([i for i in x], supp_df["corr"].values, "D-", color="#0f3460", lw=2.5, ms=9,
         markerfacecolor="white", markeredgecolor="#0f3460", markeredgewidth=2, label="Pearson Correlation")
for i, c in enumerate(supp_df["corr"]):
    ax2.annotate(f"{c:.4f}", (i, c), textcoords="offset points", xytext=(0,12), ha="center", fontsize=9, color="#0f3460")
ax1.set_xticks(x)
ax1.set_xticklabels([f"k ≥ {int(r['k_threshold'])}" for _,r in supp_df.iterrows()], fontsize=10)
ax1.set_ylabel("Records Retained (%)", fontsize=11, color="#2d6a4f")
ax2.set_ylabel("Pearson Correlation (data quality)", fontsize=11, color="#0f3460")
ax2.set_ylim(0.955, 1.003)
ax1.set_title("k-Anonymity Suppression: Data Retained vs Quality Preserved", fontweight="bold", fontsize=13)
ax2.legend(fontsize=9, loc="center right")
ax1.spines["top"].set_visible(False); ax2.spines["top"].set_visible(False)
plt.tight_layout()
fig.savefig(FIG_DIR/"figure7_suppression.png", bbox_inches="tight", dpi=150)
plt.close(fig)
print("      ✓ figure7_suppression.png")

# =========================================================================
# DIFFERENTIAL PRIVACY
# =========================================================================
print("\n[Technique 3] Differential Privacy ...")
def add_lap(tv, sens, eps): return tv + np.random.laplace(0, sens/eps)
def test_dp(frame, eps, n=100):
    tr = frame["rating_numeric"].value_counts().sort_index()
    td = frame["review_day_of_week"].value_counts()
    re, de = [], []
    for _ in range(n):
        pe = [abs(max(0,round(add_lap(tr.get(r,0),1,eps)))-tr.get(r,0))/max(tr.get(r,0),1) for r in [1,2,3,4,5]]
        re.append(np.mean(pe)*100)
        dd = [abs(max(0,round(add_lap(td[d],1,eps)))-td[d])/td[d] for d in td.index]
        de.append(np.mean(dd)*100)
    return np.mean(re), np.mean(de)

epsilons = [0.1, 0.5, 1.0, 2.0, 5.0, 10.0]
dp_rows = []
for eps in epsilons:
    re, de = test_dp(df_base, eps)
    plabel = "Very Strong" if eps<=0.5 else ("Strong" if eps<=1 else ("Moderate" if eps<=5 else "Weak"))
    dp_rows.append({"epsilon":eps,"rating_err":re,"dow_err":de,"privacy":plabel})
    print(f"      eps={eps:<5} | Rating err: {re:>5.2f}% | DoW err: {de:>5.2f}% | {plabel}")
dp_df = pd.DataFrame(dp_rows)
dp_df.to_csv(RES_DIR/"differential_privacy_results.csv", index=False)

fig, ax = plt.subplots(figsize=(8, 5))
ax.plot(dp_df["epsilon"], dp_df["rating_err"], "o-", color="#e94560", lw=2.5, ms=10,
        markerfacecolor="white", markeredgecolor="#e94560", markeredgewidth=2, label="Rating Count Error (%)")
ax.plot(dp_df["epsilon"], dp_df["dow_err"], "s-", color="#0f3460", lw=2.5, ms=10,
        markerfacecolor="white", markeredgecolor="#0f3460", markeredgewidth=2, label="Day-of-Week Error (%)")
ax.fill_between(dp_df["epsilon"], dp_df["rating_err"], alpha=0.1, color="#e94560")
ax.fill_between(dp_df["epsilon"], dp_df["dow_err"], alpha=0.1, color="#0f3460")
ax.axvspan(0, 1.05, alpha=0.06, color="#2d6a4f", label="Strong Privacy Zone (ε ≤ 1)")
ax.set_xlabel("Epsilon (ε) — Privacy Budget", fontsize=11)
ax.set_ylabel("Average Error in Aggregate Queries (%)", fontsize=11)
ax.set_title("Differential Privacy: Noise Level vs Privacy Budget", fontweight="bold", fontsize=13)
ax.legend(fontsize=9); ax.spines[["top","right"]].set_visible(False)
ax.annotate("Recommended: ε = 1\n(< 0.1% error)", xy=(1.0, dp_df[dp_df.epsilon==1.0]["rating_err"].values[0]),
            xytext=(3, 0.35), fontsize=10, fontweight="bold", color="#2d6a4f",
            arrowprops=dict(arrowstyle="->", color="#2d6a4f", lw=1.5))
plt.tight_layout()
fig.savefig(FIG_DIR/"figure8_differential_privacy.png", bbox_inches="tight", dpi=150)
plt.close(fig)
print("      ✓ figure8_differential_privacy.png")

# =========================================================================
# BEFORE vs AFTER (combined strategy)
# =========================================================================
print("\n[Combination of Techniques] Before vs After ...")
df_after = generalise(df_base, level=2)
gsz = df_after.groupby(qi_str, observed=True).transform("size")
df_combined = df_after[gsz >= 5]

after = {"uniq":uniq(df_combined,qi_str), "avg_gs":avg_gs(df_combined,qi_str),
         "at_risk":at_risk(df_combined,qi_str), "kept":len(df_combined)/len(df_base),
         "identifiable": int(uniq(df_combined,qi_str)*len(df_combined))}

print(f"      Before: Unique={base['uniq']:.2%}, Avg group={base['avg_gs']:.1f}, Identifiable={int(base['uniq']*base['n']):,}")
print(f"      After:  Unique={after['uniq']:.2%}, Avg group={after['avg_gs']:.1f}, Identifiable={after['identifiable']}")

fig, axes = plt.subplots(1, 3, figsize=(12, 4.5))

ax = axes[0]
bv, av = base["uniq"]*100, after["uniq"]*100
bars = ax.bar(["BEFORE","AFTER"], [bv, av], color=["#e94560","#2d6a4f"], edgecolor="white", width=0.5)
ax.text(0, bv+0.3, f"{bv:.1f}%", ha="center", fontsize=13, fontweight="bold")
ax.text(1, av+0.3, f"{av:.2f}%", ha="center", fontsize=13, fontweight="bold")
ax.set_ylabel("Percentage (%)")
ax.set_title("Uniqueness", fontweight="bold", fontsize=12)
ax.spines[["top","right"]].set_visible(False)

ax = axes[1]
bv2, av2 = int(base["uniq"]*base["n"]), after["identifiable"]
bars = ax.bar(["BEFORE","AFTER"], [bv2, av2], color=["#e94560","#2d6a4f"], edgecolor="white", width=0.5)
ax.text(0, bv2+50, f"{bv2:,}", ha="center", fontsize=13, fontweight="bold")
ax.text(1, av2+50, f"{av2}", ha="center", fontsize=13, fontweight="bold")
ax.set_ylabel("Number of Users")
ax.set_title("Identifiable Users", fontweight="bold", fontsize=12)
ax.spines[["top","right"]].set_visible(False)

ax = axes[2]
bv3, av3 = base["avg_gs"], after["avg_gs"]
bars = ax.bar(["BEFORE","AFTER"], [bv3, av3], color=["#e94560","#2d6a4f"], edgecolor="white", width=0.5)
ax.text(0, bv3+2, f"{bv3:.1f}", ha="center", fontsize=13, fontweight="bold")
ax.text(1, av3+2, f"{av3:.1f}", ha="center", fontsize=13, fontweight="bold")
ax.set_ylabel("Group Size")
ax.set_title("Avg Anonymity Group", fontweight="bold", fontsize=12)
ax.spines[["top","right"]].set_visible(False)

fig.suptitle("Privacy Improvement: Before vs After Mitigation", fontweight="bold", fontsize=14, y=1.02)
plt.tight_layout()
fig.savefig(FIG_DIR/"figure9_before_after.png", bbox_inches="tight", dpi=150)
plt.close(fig)
print("      ✓ figure9_before_after.png")

# =========================================================================
# ROI ANALYSIS (in South African Rands)
# =========================================================================
print("\n[Financial Analysis] ROI Analysis (ZAR) ...")

roi_components = {
    "Regulatory fines (POPIA)":      {"prob": 0.10, "max_fine": 10_000_000, "expected": 1_000_000},
    "Data breach provision (IAS37)": {"prob": 0.15, "max_cost": 17_000_000, "expected": 2_550_000},
    "Litigation exposure":           {"prob": 0.08, "max_cost":  6_000_000, "expected":   480_000},
    "Incident response":             {"prob": 1.00, "max_cost":    750_000, "expected":   750_000},
}
total_exposure = sum(v["expected"] for v in roi_components.values())
mitigation_cost = 450_000
net_benefit = total_exposure - mitigation_cost
roi_pct = (net_benefit / mitigation_cost) * 100

print(f"      Total expected exposure:  R{total_exposure:>12,}")
print(f"      Mitigation cost:          R{mitigation_cost:>12,}")
print(f"      Net benefit:              R{net_benefit:>12,}")
print(f"      ROI:                      {roi_pct:>11,.0f}%")

roi_df = pd.DataFrame([
    {"component": k, "probability": v["prob"], "expected_value_ZAR": v["expected"]}
    for k, v in roi_components.items()
] + [
    {"component": "Total Exposure", "probability": "", "expected_value_ZAR": total_exposure},
    {"component": "Mitigation Cost", "probability": "", "expected_value_ZAR": -mitigation_cost},
    {"component": "Net Benefit", "probability": "", "expected_value_ZAR": net_benefit},
    {"component": "ROI", "probability": "", "expected_value_ZAR": roi_pct},
])
roi_df.to_csv(RES_DIR/"roi_analysis.csv", index=False)

fig, ax = plt.subplots(figsize=(9, 5.5))
categories = ["Regulatory\nFines", "Breach\nProvision", "Litigation\nRisk",
              "Incident\nResponse", "Mitigation\nCost", "Net\nBenefit"]
values = [1_000_000, 2_550_000, 480_000, 750_000, -450_000, net_benefit]
colors_roi = ["#5B1A2A","#7B3F4E","#9B6070","#B88090","#e94560","#2d6a4f"]

bars = ax.bar(range(len(categories)), [v/1e6 for v in values], color=colors_roi,
              edgecolor="white", width=0.55)
for b, v in zip(bars, values):
    label = f"R{abs(v)/1e6:.2f}M" if abs(v) >= 1e6 else f"R{abs(v)/1e3:.0f}K"
    if v < 0: label = f"-{label}"
    if v >= 0:
        ypos = b.get_height() + 0.08
    else:
        ypos = b.get_height() - 0.25
    ax.text(b.get_x()+b.get_width()/2, ypos, label, ha="center", fontsize=11, fontweight="bold",
            color="#333333")

ax.set_ylim(-0.8, 5.2)

ax.axhline(0, color="black", lw=0.8)
ax.set_xticks(range(len(categories))); ax.set_xticklabels(categories, fontsize=9)
ax.set_ylabel("Value (R Millions)", fontsize=11)
ax.set_title(f"Risk-Adjusted ROI: Privacy Controls vs Expected Breach Costs\nROI = {roi_pct:.0f}%",
             fontweight="bold", fontsize=13)
ax.spines[["top","right"]].set_visible(False)
plt.tight_layout()
fig.savefig(FIG_DIR/"figure10_roi.png", bbox_inches="tight", dpi=150)
plt.close(fig)
print("      ✓ figure10_roi.png")

# =========================================================================
# SAVING COMBINED RECOMMENDATION
# =========================================================================
pd.DataFrame([{
    "strategy": "Gen L2 + Suppression k>=5 + DP eps=1",
    "uniqueness_before": f"{base['uniq']:.2%}",
    "uniqueness_after": f"{after['uniq']:.2%}",
    "avg_group_before": f"{base['avg_gs']:.1f}",
    "avg_group_after": f"{after['avg_gs']:.1f}",
    "data_retained": f"{after['kept']:.1%}",
    "roi_pct": f"{roi_pct:.0f}%",
    "net_benefit_ZAR": f"R{net_benefit:,}",
}]).to_csv(RES_DIR/"combined_recommendation.csv", index=False)

# =========================================================================
# END OF TASK B
# =========================================================================
print("\n" + "=" * 72)
print("  TASK B COMPLETE — outputs in:", OUT_DIR)
print("=" * 72)
print(f"""
  GRAPH OUTPUTS:
      figure6_generalisation.png
      figure7_suppression.png
      figure8_differential_privacy.png
      figure9_before_after.png
      figure10_roi.png

  CSV RESULTS:
    generalisation_results.csv
    suppression_results.csv
    differential_privacy_results.csv
    roi_analysis.csv
    combined_recommendation.csv
""")