# -*- coding: utf-8 -*-
"""github ready A01A.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GsMjuVE7L9vHaNcTw_cihwqXg5C5IGcq
"""

"""
================================================================================
Data Privacy & Re-Identification Risk in Amazon Review Data
================================================================================
Author: Franco Saayman

Ethical Challenge : Data Privacy and Re-Identification
Dataset          : Amazon_Reviews.csv (in the SAME folder as this script)
Trajectory       : Business Understanding > Data Understanding > Data Preparation
                   > Evaluation > Deployment  (Modelling phase EXCLUDED)

Run:
    pip install pandas numpy scipy matplotlib seaborn
    python task_a.py

Outputs (created in ./task_a_outputs/):
    figures/fig1_eda_overview.png
    figures/fig2_reidentification_risk.png
    figures/fig3_linkage_attack.png
    figures/fig4_crisp_dm_trajectory.png
    figures/fig5_entropy_heatmap.png
    results/qi_uniqueness_results.csv
    results/linkage_attack_results.csv
    results/synthetic_reviews.csv
================================================================================
"""

import os, sys, random, warnings, string, datetime
from pathlib import Path
from itertools import combinations

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import matplotlib.patches as mpatches
from matplotlib.patches import FancyBboxPatch
import seaborn as sns
from scipy.stats import entropy as scipy_entropy

warnings.filterwarnings("ignore")
np.random.seed(42)
random.seed(42)

# Simple synthetic name & date generators without external library or libraries
_FIRST = ["James","Mary","John","Patricia","Robert","Jennifer","Michael",
          "Linda","David","Elizabeth","William","Barbara","Richard","Susan",
          "Joseph","Jessica","Thomas","Sarah","Charles","Karen","Daniel",
          "Lisa","Matthew","Nancy","Anthony","Betty","Mark","Margaret",
          "Donald","Sandra","Steven","Ashley","Andrew","Dorothy","Paul",
          "Kimberly","Joshua","Emily","Kenneth","Donna","Kevin","Michelle",
          "Brian","Carol","George","Amanda","Timothy","Melissa","Ronald",
          "Deborah","Edward","Stephanie","Jason","Rebecca","Jeffrey","Sharon"]
_LAST  = ["Smith","Johnson","Williams","Brown","Jones","Garcia","Miller",
          "Davis","Rodriguez","Martinez","Hernandez","Lopez","Gonzalez",
          "Wilson","Anderson","Thomas","Taylor","Moore","Jackson","Martin",
          "Lee","Perez","Thompson","White","Harris","Sanchez","Clark",
          "Ramirez","Lewis","Robinson","Walker","Young","Allen","King",
          "Wright","Scott","Torres","Nguyen","Hill","Flores","Green",
          "Adams","Nelson","Baker","Hall","Rivera","Campbell","Mitchell"]

def _rand_name():
    return random.choice(_FIRST) + " " + random.choice(_LAST)

def _rand_date(start_year=2021):
    start = datetime.date(start_year, 1, 1)
    end   = datetime.date(2024, 9, 15)
    delta = (end - start).days
    return start + datetime.timedelta(days=random.randint(0, delta))

# 0.  PATHS
SCRIPT_DIR = Path(__file__).resolve().parent
DATA_FILE  = SCRIPT_DIR / "Amazon_Reviews.csv"
OUT_DIR    = SCRIPT_DIR / "task_a_outputs"
FIG_DIR    = OUT_DIR / "figures"
RES_DIR    = OUT_DIR / "results"

for d in [FIG_DIR, RES_DIR]:
    d.mkdir(parents=True, exist_ok=True)

if not DATA_FILE.exists():
    sys.exit(f"ERROR: Cannot find '{DATA_FILE.name}' in {SCRIPT_DIR}\n"
             f"Place Amazon_Reviews.csv in the same folder as this script.")

print("=" * 72)
print("  Data Privacy & Re-Identification Risk Analysis")
print("  Author: Franco Saayman")
print("=" * 72)

plt.rcParams.update({"font.size": 10, "figure.dpi": 150, "axes.titlesize": 12,
                      "axes.labelsize": 10, "figure.facecolor": "white"})

# =========================================================================
# 1.  DATA CLEANING & FEATURE ENGINEERING
# =========================================================================
print("\n[1/6] Loading and cleaning data ...")

df_raw = pd.read_csv(DATA_FILE, on_bad_lines="skip", engine="python")
print(f"      Raw rows loaded: {len(df_raw):,}")
df = df_raw.copy()
df["rating_numeric"] = df["Rating"].str.extract(r"Rated (\d) out of").astype(float)
df["review_datetime"] = pd.to_datetime(df["Review Date"], format="mixed", utc=True, errors="coerce")
df["review_date_clean"]  = df["review_datetime"].dt.date
df["review_month"]       = df["review_datetime"].dt.to_period("M").astype(str)
df["review_day_of_week"] = df["review_datetime"].dt.day_name()
df["review_hour"]        = df["review_datetime"].dt.hour
df["review_count_numeric"] = df["Review Count"].str.extract(r"(\d+)").astype(float)
df["review_length"]    = df["Review Text"].fillna("").str.len()
df["word_count"]       = df["Review Text"].fillna("").str.split().str.len()
df["avg_word_length"]  = df["Review Text"].fillna("").apply(
    lambda x: np.mean([len(w) for w in x.split()]) if x.split() else 0)
df["exclamation_count"] = df["Review Text"].fillna("").str.count("!")
df["uppercase_ratio"]   = df["Review Text"].fillna("").apply(
    lambda x: sum(c.isupper() for c in x) / max(len(x), 1))
df["review_length_bin"] = pd.cut(df["review_length"],
    bins=[0, 100, 250, 500, 1000, 5000, float("inf")],
    labels=["Very Short", "Short", "Medium", "Long", "Very Long", "Extremely Long"])
df["word_count_bin"] = pd.cut(df["word_count"],
    bins=[0, 20, 50, 100, 200, float("inf")], labels=["<20", "20-50", "50-100", "100-200", "200+"])
df["hour_bin"] = pd.cut(df["review_hour"],
    bins=[-1, 6, 12, 18, 24], labels=["Night(0-6)", "Morning(7-12)", "Afternoon(13-18)", "Evening(19-24)"])
df = df.dropna(subset=["rating_numeric", "review_datetime", "Country", "Reviewer Name"])
print(f"      Clean rows: {len(df):,}")
print(f"      Unique reviewers: {df['Reviewer Name'].nunique():,}")
print(f"      Countries: {df['Country'].nunique()}")
print(f"      Date range: {df['review_date_clean'].min()} to {df['review_date_clean'].max()}")

# =========================================================================
# 2.  EDA OVERVIEW
# =========================================================================
print("\n[2/6] Generating EDA visualisations ...")
fig = plt.figure(figsize=(14, 10)); gs = gridspec.GridSpec(2, 2, hspace=0.35, wspace=0.3)
bar_colors = ["#1a1a2e", "#16213e", "#0f3460", "#533483", "#e94560"]
ax = fig.add_subplot(gs[0, 0])
rc = df["rating_numeric"].value_counts().sort_index()
bars = ax.bar(rc.index.astype(int), rc.values, color=bar_colors, edgecolor="white")
for b, v in zip(bars, rc.values): ax.text(b.get_x()+b.get_width()/2, b.get_height()+150, f"{v:,}", ha="center", fontsize=9, fontweight="bold")
ax.set_xlabel("Rating (Stars)"); ax.set_ylabel("Number of Reviews"); ax.set_title("(a) Rating Distribution", fontweight="bold"); ax.set_xticks([1,2,3,4,5]); ax.spines[["top","right"]].set_visible(False)
ax = fig.add_subplot(gs[0, 1])
tc = df["Country"].value_counts().head(10)
ax.barh(range(len(tc)), tc.values, color=sns.color_palette("viridis", 10)); ax.set_yticks(range(len(tc))); ax.set_yticklabels(tc.index); ax.invert_yaxis()
for i, v in enumerate(tc.values): ax.text(v+50, i, f"{v:,}", va="center", fontsize=9)
ax.set_xlabel("Number of Reviews"); ax.set_title("(b) Top 10 Countries by Review Volume", fontweight="bold"); ax.spines[["top","right"]].set_visible(False)
ax = fig.add_subplot(gs[1, 0])
ax.hist(df["review_length"].clip(upper=2000), bins=60, color="#0f3460", edgecolor="white", linewidth=0.3, alpha=0.8)
ml = df["review_length"].median(); ax.axvline(ml, color="#e94560", ls="--", lw=2, label=f"Median: {ml:.0f} chars")
ax.set_xlabel("Review Length (chars, capped 2000)"); ax.set_ylabel("Frequency"); ax.set_title("(c) Review Length Distribution", fontweight="bold"); ax.legend(fontsize=9); ax.spines[["top","right"]].set_visible(False)
ax = fig.add_subplot(gs[1, 1])
hc = df["review_hour"].value_counts().sort_index(); ax.fill_between(hc.index, hc.values, alpha=0.3, color="#533483"); ax.plot(hc.index, hc.values, color="#533483", lw=2)
ax.set_xlabel("Hour of Day (UTC)"); ax.set_ylabel("Number of Reviews"); ax.set_title("(d) Posting Time Distribution", fontweight="bold"); ax.set_xticks(range(0,24,3)); ax.spines[["top","right"]].set_visible(False)
fig.suptitle("Amazon Review Dataset - Exploratory Data Analysis\nData Privacy Risk Assessment | Franco Saayman", fontsize=14, fontweight="bold", y=1.02)
fig.savefig(FIG_DIR/"figure1_eda_overview.png", bbox_inches="tight", dpi=150); plt.close(fig)
print("      Done figure1_eda_overview.png")

# =========================================================================
# 3.  QUASI-IDENTIFIER UNIQUENESS ANALYSIS
# =========================================================================
print("\n[3/6] Quasi-identifier uniqueness analysis ...")
QI_DEFS = {"Country":"Country","Rating":"rating_numeric","Day of Week":"review_day_of_week","Hour Bin":"hour_bin","Length Bin":"review_length_bin","Word Ct Bin":"word_count_bin"}
qi_names = list(QI_DEFS.keys()); qi_cols = list(QI_DEFS.values())
def compute_uniqueness(frame, cols):
    gs = frame.groupby(cols, observed=True).size(); return (gs==1).sum()/len(frame)
def compute_k(frame, cols):
    return frame.groupby(cols, observed=True).size().min()
def field_entropy(series):
    p = series.value_counts(normalize=True).values; return scipy_entropy(p, base=2)
def joint_entropy(frame, cols):
    combined = frame[cols].astype(str).apply(tuple, axis=1); p = combined.value_counts(normalize=True).values; return scipy_entropy(p, base=2)

results = []
for n in range(1, len(qi_cols)+1):
    for combo in combinations(range(len(qi_cols)), n):
        c_names = [qi_names[i] for i in combo]; c_cols = [qi_cols[i] for i in combo]
        sub = df.dropna(subset=c_cols)
        results.append({"n_qi":n, "combination":" + ".join(c_names), "uniqueness":compute_uniqueness(sub,c_cols), "k_anonymity":compute_k(sub,c_cols), "joint_entropy":joint_entropy(sub,c_cols), "n_records":len(sub)})
res_df = pd.DataFrame(results); res_df.to_csv(RES_DIR/"qi_uniqueness_results.csv", index=False)
avg_by_n = res_df.groupby("n_qi").agg(avg_uniq=("uniqueness","mean"), max_uniq=("uniqueness","max"), min_k=("k_anonymity","min")).reset_index()
for _, r in avg_by_n.iterrows(): print(f"      {int(r['n_qi'])} QIs: avg unique {r['avg_uniq']:.1%}, max unique {r['max_uniq']:.1%}, min k={int(r['min_k'])}")

fig = plt.figure(figsize=(18, 11)); gs2 = gridspec.GridSpec(2, 2, hspace=0.4, wspace=0.75, width_ratios=[1, 1.6])
ax = fig.add_subplot(gs2[0, 0])
bp_data = [res_df[res_df["n_qi"]==n]["uniqueness"].values for n in range(1,7)]
bp = ax.boxplot(bp_data, positions=range(1,7), patch_artist=True, widths=0.6, medianprops=dict(color="white", lw=2))
for patch, c in zip(bp["boxes"], plt.cm.Reds(np.linspace(0.3,0.9,6))): patch.set_facecolor(c)
ax.set_xlabel("Number of Quasi-Identifiers Combined"); ax.set_ylabel("Proportion Uniquely Identified"); ax.set_title("(a) Re-ID Risk Grows with\nQuasi-Identifier Combinations", fontweight="bold"); ax.spines[["top","right"]].set_visible(False); ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda y,_: f"{y:.0%}"))
ax = fig.add_subplot(gs2[0, 1])
top10 = res_df.nlargest(10,"uniqueness"); pal = plt.cm.Reds(np.linspace(0.4,0.9,10))[::-1]
bars = ax.barh(range(10), top10["uniqueness"].values, color=pal); ax.set_yticks(range(10)); ax.set_yticklabels(top10["combination"].values, fontsize=7); ax.invert_yaxis()
for b, v in zip(bars, top10["uniqueness"].values): ax.text(b.get_width()+0.004, b.get_y()+b.get_height()/2, f"{v:.1%}", va="center", fontsize=9, fontweight="bold")
ax.set_xlabel("Proportion Uniquely Identified"); ax.set_title("(b) Top 10 Most Identifying\nQI Combinations", fontweight="bold"); ax.spines[["top","right"]].set_visible(False); ax.xaxis.set_major_formatter(plt.FuncFormatter(lambda y,_: f"{y:.0%}"))
ax = fig.add_subplot(gs2[1, 0])
ent = {n: field_entropy(df[c].dropna()) for n,c in QI_DEFS.items()}; ent_s = pd.Series(ent).sort_values()
ax.barh(ent_s.index, ent_s.values, color=plt.cm.YlOrRd(np.linspace(0.3,0.8,len(ent_s))))
for i, (idx,v) in enumerate(ent_s.items()): ax.text(v+0.08, i, f"{v:.2f} bits", va="center", fontsize=9)
ax.set_xlabel("Shannon Entropy (bits)"); ax.set_title("(c) Identifying Power of Each\nQuasi-Identifier", fontweight="bold"); ax.spines[["top","right"]].set_visible(False)
ax = fig.add_subplot(gs2[1, 1])
worst = top10.iloc[0]; worst_cols = [QI_DEFS[n] for n in worst["combination"].split(" + ")]
ec = df.dropna(subset=worst_cols).groupby(worst_cols, observed=True).size()
bins_ec = [1,2,3,5,10,20,50,100,500]; labels_ec = ["1","2","3-4","5-9","10-19","20-49","50-99","100+"]
counts_ec = [];
for i in range(len(bins_ec)-1): counts_ec.append(((ec>=bins_ec[i])&(ec<bins_ec[i+1])).sum())
counts_ec.append((ec>=bins_ec[-1]).sum())
bar_c = ["#e94560" if i==0 else "#0f3460" for i in range(len(labels_ec))]
ax.bar(range(len(labels_ec)), counts_ec[:len(labels_ec)], color=bar_c, edgecolor="white"); ax.set_xticks(range(len(labels_ec))); ax.set_xticklabels(labels_ec, fontsize=8)
ax.set_xlabel("Equivalence Class Size"); ax.set_ylabel("Number of Classes"); ax.set_title(f"(d) Equivalence Class Sizes\n({worst['combination'][:45]})", fontweight="bold", fontsize=10); ax.spines[["top","right"]].set_visible(False)
if counts_ec[0]>0: ax.annotate(f"{counts_ec[0]:,} unique\nrecords!", xy=(0,counts_ec[0]), xytext=(1.5,counts_ec[0]*0.8), fontsize=9, color="#e94560", fontweight="bold", arrowprops=dict(arrowstyle="->", color="#e94560"))
fig.suptitle("Quasi-Identifier Analysis - Re-Identification Risk in Amazon Reviews\nData Privacy Risk Assessment | Franco Saayman", fontsize=14, fontweight="bold", y=1.02)
fig.savefig(FIG_DIR/"figure2_reidentification_risk.png", bbox_inches="tight", dpi=150); plt.close(fig)
print("      Done figure2_reidentification_risk.png")

# =========================================================================
# 4.  SYNTHETIC DATA GENERATION & LINKAGE ATTACK SIMULATION
# =========================================================================
print("\n[4/6] Generating synthetic data & simulating linkage attack ...")
COUNTRIES = ["US","GB","CA","IN","IE","DE","AU","NL","IT","FR","DK","BR","JP","ZA","NG","KE","MX","ES","SE","PH"]
C_WEIGHTS = [.40,.30,.05,.04,.02,.02,.02,.01,.01,.01,.01,.01,.01,.01,.01,.01,.01,.01,.01,.03]
N_REVIEWERS = 1000; profiles, reviews = [], []
for rid in range(N_REVIEWERS):
    p = dict(gid=f"R{rid:05d}", name=_rand_name(), country=np.random.choice(COUNTRIES, p=C_WEIGHTS), rat_mu=np.clip(np.random.normal(3.2,1.2),1,5), rat_sd=np.clip(np.random.exponential(0.8),0.2,1.5), hr_mu=np.random.uniform(6,22), hr_sd=np.random.uniform(1.5,4), len_mu=np.random.lognormal(5,0.7), wl_mu=np.clip(np.random.normal(4.8,0.5),3.5,6.5), exc_rate=np.random.beta(2,10))
    profiles.append(p)
    for _ in range(max(1, int(np.random.poisson(12)))):
        rd = _rand_date()
        reviews.append(dict(ground_truth_id=p["gid"], true_name=p["name"], country=p["country"], rating=int(np.clip(round(np.random.normal(p["rat_mu"],p["rat_sd"])),1,5)), review_date=rd, posting_hour=int(np.clip(np.random.normal(p["hr_mu"],p["hr_sd"]),0,23)), review_length=max(20,int(np.random.normal(p["len_mu"],p["len_mu"]*0.3))), avg_word_length=round(np.clip(np.random.normal(p["wl_mu"],0.3),3,7),2), exclamation_count=int(np.random.poisson(p["exc_rate"]*5)), day_of_week=rd.strftime("%A")))
df_synth = pd.DataFrame(reviews); df_synth.to_csv(RES_DIR/"synthetic_reviews.csv", index=False)
print(f"      Synthetic reviews generated: {len(df_synth):,}")

df_tgt = df_synth.groupby("ground_truth_id").agg(country=("country","first"), avg_rating=("rating","mean"), common_hour=("posting_hour", lambda x: x.mode().iloc[0] if len(x.mode()) else 12), avg_length=("review_length","mean")).reset_index()
df_aux = pd.DataFrame([dict(known_name=p["name"], known_country=p["country"], known_avg_rating=df_synth[df_synth.ground_truth_id==p["gid"]]["rating"].mean(), known_common_hour=df_synth[df_synth.ground_truth_id==p["gid"]]["posting_hour"].mode().iloc[0] if len(df_synth[df_synth.ground_truth_id==p["gid"]]["posting_hour"].mode()) else 12, known_avg_length=df_synth[df_synth.ground_truth_id==p["gid"]]["review_length"].mean(), ground_truth_id=p["gid"]) for p in profiles if len(df_synth[df_synth.ground_truth_id==p["gid"]])>0])

def linkage_attack(tgt, aux, tgt_qi, aux_qi, tol=None):
    correct=incorrect=unlinked=0
    for _, ar in aux.iterrows():
        mask = pd.Series(True, index=tgt.index)
        for tq, aq in zip(tgt_qi, aux_qi):
            if tol and tq in tol: mask &= (tgt[tq]-ar[aq]).abs()<=tol[tq]
            else: mask &= tgt[tq]==ar[aq]
        m = tgt[mask]
        if len(m)==0: unlinked+=1
        elif len(m)==1:
            if m.iloc[0]["ground_truth_id"]==ar["ground_truth_id"]: correct+=1
            else: incorrect+=1
        else:
            uids = m["ground_truth_id"].unique()
            if len(uids)==1 and uids[0]==ar["ground_truth_id"]: correct+=1
            else: unlinked+=1
    return correct, incorrect, unlinked

SCENARIOS = [("1 QI: Country",["country"],["known_country"],{}),("2 QIs: Country + Rating",["country","avg_rating"],["known_country","known_avg_rating"],{"avg_rating":0.3}),("3 QIs: + Hour",["country","avg_rating","common_hour"],["known_country","known_avg_rating","known_common_hour"],{"avg_rating":0.3,"common_hour":1}),("4 QIs: + Length",["country","avg_rating","common_hour","avg_length"],["known_country","known_avg_rating","known_common_hour","known_avg_length"],{"avg_rating":0.3,"common_hour":1,"avg_length":50})]
link_res = []
for name, tqi, aqi, tol in SCENARIOS:
    c, ic, ul = linkage_attack(df_tgt, df_aux, tqi, aqi, tol); tot=c+ic+ul
    link_res.append(dict(scenario=name, correct=c, incorrect=ic, unlinked=ul, reid_rate=c/tot))
    print(f"      {name:40s} -> re-ID {c/tot:.1%}  (correct={c}, incorrect={ic}, unlinked={ul})")
link_df = pd.DataFrame(link_res); link_df.to_csv(RES_DIR/"linkage_attack_results.csv", index=False)

fig = plt.figure(figsize=(14, 10)); gs3 = gridspec.GridSpec(2, 2, hspace=0.4, wspace=0.3)
ax = fig.add_subplot(gs3[0, 0]); rates=[r["reid_rate"] for r in link_res]; bc=["#2d6a4f","#40916c","#d4a373","#e94560"]
bars = ax.bar([1,2,3,4], rates, color=bc, edgecolor="white", width=0.6)
for b,v in zip(bars,rates): ax.text(b.get_x()+b.get_width()/2, b.get_height()+0.01, f"{v:.1%}", ha="center", fontsize=11, fontweight="bold")
ax.set_xlabel("Number of Quasi-Identifiers in Attack"); ax.set_ylabel("Re-Identification Success Rate"); ax.set_title("(a) Linkage Attack Success\nIncreases with More QIs", fontweight="bold"); ax.set_xticks([1,2,3,4]); ax.set_ylim(0, max(rates)*1.25); ax.spines[["top","right"]].set_visible(False); ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda y,_: f"{y:.0%}"))
ax = fig.add_subplot(gs3[0, 1]); labs=["1 QI","2 QIs","3 QIs","4 QIs"]; cv=[r["correct"] for r in link_res]; iv=[r["incorrect"] for r in link_res]; uv=[r["unlinked"] for r in link_res]
ax.bar(labs,cv,label="Correctly Linked",color="#e94560"); ax.bar(labs,iv,bottom=cv,label="Incorrectly Linked",color="#ffd166"); ax.bar(labs,uv,bottom=[c+i for c,i in zip(cv,iv)],label="Unlinked (Safe)",color="#2d6a4f")
ax.set_ylabel("Reviewers"); ax.legend(fontsize=8); ax.set_title("(b) Linkage Attack Outcomes", fontweight="bold"); ax.spines[["top","right"]].set_visible(False)
ax = fig.add_subplot(gs3[1, 0]); real_r=df["rating_numeric"].value_counts(normalize=True).sort_index(); syn_r=df_synth["rating"].value_counts(normalize=True).sort_index(); x=np.arange(1,6); w=0.3
ax.bar(x-w/2, [real_r.get(i,0) for i in range(1,6)], w, label="Real Amazon Data", color="#0f3460", alpha=0.8); ax.bar(x+w/2, [syn_r.get(i,0) for i in range(1,6)], w, label="Synthetic Data", color="#e94560", alpha=0.8)
ax.set_xlabel("Rating"); ax.set_ylabel("Proportion"); ax.set_xticks(x); ax.set_title("(c) Rating Distributions:\nReal vs Synthetic", fontweight="bold"); ax.legend(fontsize=9); ax.spines[["top","right"]].set_visible(False)
ax = fig.add_subplot(gs3[1, 1]); qi_syn=["country","rating","day_of_week","posting_hour"]; qi_lab=["Country","+Rating","+Day","+Hour"]; uv2=[]
for i in range(1,len(qi_syn)+1): c2=qi_syn[:i]; g=df_synth.groupby(c2).size(); uv2.append((g==1).sum()/len(df_synth))
ax.plot(range(1,5), uv2, "o-", color="#e94560", lw=2.5, ms=10, markerfacecolor="white", markeredgecolor="#e94560", mew=2)
for i,(u,l) in enumerate(zip(uv2,qi_lab)): ax.annotate(f"{l}\n{u:.1%}", (i+1,u), textcoords="offset points", xytext=(0,15), ha="center", fontsize=8, fontweight="bold")
ax.set_xlabel("Cumulative Quasi-Identifiers"); ax.set_ylabel("Proportion Uniquely Identified"); ax.set_title("(d) Uniqueness Growth in\nSynthetic Data (Netflix-style)", fontweight="bold"); ax.set_xticks(range(1,5)); ax.set_ylim(bottom=0); ax.spines[["top","right"]].set_visible(False); ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda y,_: f"{y:.0%}"))
fig.suptitle("Synthetic Data Linkage Attack - Demonstrating Re-Identification Risk\nData Privacy Risk Assessment | Franco Saayman", fontsize=14, fontweight="bold", y=1.02)
fig.savefig(FIG_DIR/"figure3_linkage_attack.png", bbox_inches="tight", dpi=150); plt.close(fig)
print("      Done figure3_linkage_attack.png")

# =========================================================================
# 5.  CRISP-DM TRAJECTORY DIAGRAM
# =========================================================================
print("\n[5/6] Generating CRISP-DM trajectory diagram ...")
fig, ax = plt.subplots(figsize=(14, 8)); ax.set_xlim(0,14); ax.set_ylim(0,8); ax.axis("off")
phases = [("Business\nUnderstanding",1,5.5,"#1a1a2e","Define privacy threat model:\n\"Can reviewers be re-identified\nfrom Amazon review data?\""),("Data\nUnderstanding",3.5,5.5,"#16213e","Explore quasi-identifiers,\nassess data quality,\nidentify re-ID vectors"),("Data\nPreparation",6,5.5,"#0f3460","Clean data, compute k-anonymity,\ngenerate synthetic data,\ncreate QI cross-tabs"),("Evaluation",8.5,5.5,"#533483","Quantify re-ID risk,\nlinkage attack simulation,\nprivacy-utility trade-off"),("Deployment",11,5.5,"#e94560","Privacy risk report,\nmitigation dashboards,\nROI recommendations")]
for name,x,y,col,detail in phases:
    ax.add_patch(FancyBboxPatch((x-0.9,y-0.5),1.8,1.2,boxstyle="round,pad=0.1",facecolor=col,edgecolor="white",lw=2)); ax.text(x,y+0.1,name,ha="center",va="center",fontsize=10,fontweight="bold",color="white")
    ax.add_patch(FancyBboxPatch((x-1,y-2.2),2,1.5,boxstyle="round,pad=0.1",facecolor="#f8f9fa",edgecolor=col,lw=1.5)); ax.text(x,y-1.45,detail,ha="center",va="center",fontsize=7.5,color="#333")
for i in range(len(phases)-1): ax.annotate("",xy=(phases[i+1][1]-0.95,phases[i+1][2]),xytext=(phases[i][1]+0.95,phases[i][2]),arrowprops=dict(arrowstyle="->",color="#666",lw=2.5))
mx,my=6,7.2; ax.add_patch(FancyBboxPatch((mx-0.9,my-0.4),1.8,0.8,boxstyle="round,pad=0.1",facecolor="#ddd",edgecolor="#999",lw=1.5,linestyle="--")); ax.text(mx,my,"Modelling\n(EXCLUDED)",ha="center",va="center",fontsize=9,color="#999",fontstyle="italic")
ax.plot([mx-0.7,mx+0.7],[my-0.3,my+0.3],"r-",lw=3,alpha=0.7); ax.plot([mx-0.7,mx+0.7],[my+0.3,my-0.3],"r-",lw=3,alpha=0.7)
for name,x,y,li in [("Data Value\nExploration",2.2,1.8,1),("Result\nExploration",6,1.8,3),("Narrative\nExploration",9.8,1.8,4)]:
    ax.add_patch(plt.Circle((x,y),0.65,facecolor="#d4a373",edgecolor="white",lw=1.5,alpha=0.8)); ax.text(x,y,name,ha="center",va="center",fontsize=7.5,fontweight="bold",color="white")
    ax.annotate("",xy=(phases[li][1],phases[li][2]-0.55),xytext=(x,y+0.7),arrowprops=dict(arrowstyle="->",color="#d4a373",lw=1.5,linestyle="--"))
ax.text(7,7.8,"Data Science Trajectory - Privacy Risk Assessment (No Modelling)",ha="center",fontsize=14,fontweight="bold")
ax.text(7,7.4,"Based on Martinez-Plumed et al. (2019) CRISP-DM Twenty Years Later",ha="center",fontsize=9,fontstyle="italic",color="#666")
ax.legend(handles=[mpatches.Patch(fc="#0f3460",label="Core DST Phases (Inner Circle)"),mpatches.Patch(fc="#d4a373",label="Exploratory Activities (Outer Circle)"),mpatches.Patch(fc="#ddd",ec="#999",ls="--",label="Excluded Phase")],loc="lower right",fontsize=9)
fig.savefig(FIG_DIR/"figure4_crisp_dm_trajectory.png", bbox_inches="tight", dpi=150); plt.close(fig)
print("      Done figure4_crisp_dm_trajectory.png")

# =========================================================================
# 6.  JOINT ENTROPY HEATMAP
# =========================================================================
print("\n[6/6] Generating entropy heatmap ...")
names_h=list(QI_DEFS.keys()); cols_h=list(QI_DEFS.values()); n_h=len(names_h)
H=np.zeros((n_h,n_h))
for i in range(n_h):
    for j in range(n_h):
        if i==j: H[i,j]=field_entropy(df[cols_h[i]].dropna())
        else: H[i,j]=joint_entropy(df,[cols_h[i],cols_h[j]])
fig, ax = plt.subplots(figsize=(9,7))
sns.heatmap(H, annot=True, fmt=".2f", cmap="YlOrRd", xticklabels=names_h, yticklabels=names_h, ax=ax, linewidths=0.5, linecolor="white", cbar_kws={"label":"Entropy (bits)"})
ax.set_title("Joint Entropy Matrix - Identifying Power of QI Pairs\n(Diagonal = Individual Entropy | Off-diagonal = Joint Entropy)", fontweight="bold", fontsize=12)
ax.text(0.5,-0.1,"Higher joint entropy -> more distinguishable records -> greater re-ID risk", transform=ax.transAxes, ha="center", fontsize=9, fontstyle="italic", color="#666")
plt.tight_layout(); fig.savefig(FIG_DIR/"figure5_entropy_heatmap.png", bbox_inches="tight", dpi=150); plt.close(fig)
print("      Done figure5_entropy_heatmap.png")

# =========================================================================
# END OF TASK A
# =========================================================================
print("\n" + "=" * 72)
print("  TASK A COMPLETE - all outputs in:", OUT_DIR)
print("=" * 72)
print(f"\n  Figures:  {FIG_DIR}")
print(f"  Results:  {RES_DIR}")